Repository triggermesh/triggermesh, pull requests merged in 2022-01, with the labels that each got.

#422 List env vars required by the AWS SDK for documentation purposes
  pkg/sources/adapter/awscloudwatchlogssource/adapter.go
  pkg/sources/adapter/awscloudwatchsource/adapter.go
  pkg/sources/adapter/awscodecommitsource/adapter.go
  pkg/sources/adapter/awscognitoidentitysource/adapter.go
  pkg/sources/adapter/awscognitouserpoolsource/adapter.go
  pkg/sources/adapter/awsdynamodbsource/adapter.go
  pkg/sources/adapter/awskinesissource/adapter.go
  pkg/sources/adapter/awsperformanceinsightssource/adapter.go
  pkg/sources/adapter/awssqssource/adapter.go
Labels: documentation

#409 Add Azure source e2e tests
  .github/workflows/e2e-tests.yaml
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/LICENSE.txt
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/LICENSE.txt
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/internal/LICENSE.txt
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub/LICENSE.txt
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/iothub/armiothub/LICENSE.txt
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources/LICENSE.txt
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/LICENSE.txt
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/LICENSE.txt
  LICENSES/vendor/github.com/pkg/browser/LICENSE
  Makefile
  go.mod
  go.sum
  test/e2e/framework/azure/azure.go
  test/e2e/framework/azure/blobstorage.go
  test/e2e/framework/azure/eventhub.go
  test/e2e/framework/azure/iothub.go
  test/e2e/framework/azure/queuestorage.go
  test/e2e/framework/azure/servicebus.go
  test/e2e/sources/azureactivitylogs/main.go
  test/e2e/sources/azureblobstorage/main.go
  test/e2e/sources/azureeventgrid/main.go
  test/e2e/sources/azureeventhubs/main.go
  test/e2e/sources/azureiothub/main.go
  test/e2e/sources/azurequeuestorage/main.go
  test/e2e/sources/azureservicebusqueue/main.go
  test/e2e/sources/azureservicebustopic/main.go
  test/e2e/sources/main.go
Labels: testing

#458 Updates to Include Missing Event Type Registry Entries
  config/301-awscomprehendtarget.yaml
  config/301-azureeventhubstarget.yaml
  config/301-confluenttarget.yaml
  config/301-httptarget.yaml
  config/301-infratarget.yaml
  config/301-logztarget.yaml
  config/301-oracletarget.yaml
  config/301-splunktarget.yaml
  config/302-filter.yaml
  config/302-splitter.yaml
  config/303-function.yaml
  config/304-transformation.yaml
  config/304-xmltojsontransformation.yaml
  config/304-xslttransform.yaml
Labels: XMLToJSONTransformation, AWSComprehendTarget, AzureEventHubsTarget, ConfluentTarget, HTTPTarget, InfraJSTarget, LogzTarget, OracleTarget, SplunkTarget

#481 Azure EventHub fixes
  config/301-azureeventhubstarget.yaml
  pkg/apis/targets/v1alpha1/register.go
  pkg/targets/adapter/azureeventhubstarget/adapter.go
  pkg/targets/adapter/azureeventhubstarget/config.go
Labels: bug

#516 Introduce Azure EventHubs Target e2e test
  test/e2e/targets/azureeventhubs/main.go
  test/e2e/targets/main.go
Labels: Targets, testing

#524 Enable support for discardCEContext and send CloudEvent data as a JSON payload for the Azure Event Hubs target
  config/301-azureeventhubstarget.yaml
  pkg/apis/targets/v1alpha1/azureeventhubs_types.go
  pkg/targets/adapter/azureeventhubstarget/adapter.go
  test/e2e/targets/azureeventhubs/main.go
Labels: bug
